SuDiscussions_Mk2/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SuDiscussionsDAO;

namespace SuDiscussions_Mk2.Controllers
{
    public class AdminsController : Controller
    {
        private SuDiscussDBEntities db = new SuDiscussDBEntities();

        // GET: Admins
        public ActionResult Index()
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login");
                }
                return View();
            }
            catch(NullReferenceException nosession) { return RedirectToAction("Login"); }
        }

        public ActionResult Login()
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 1)
                    return RedirectToAction("Logout");

                return View();
            }
            catch(NullReferenceException nosesion) { return View();     }
        }

        [HttpPost]
        public ActionResult Login(Admin admin)
        {
            var L1 = from adm in db.Admins orderby adm.id select adm;

            if (ModelState.IsValid)
            {


                foreach (Admin adminlist in L1)
                {
                    if (adminlist.username == admin.username && adminlist.password == admin.password)
                    {
                        this.Session["loggedin_admin"] = 1;

                        return RedirectToAction("Index");
                    }

                }
                ModelState.AddModelError("incorrect", "Username or Password Incorrect!");
            }
            return View(admin);
        }

        public ActionResult Logout()
        {
            this.Session["loggedin_admin"] = 0;

            return RedirectToAction("Login");
        }

        // GET: Admins/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Admin admin = db.Admins.Find(id);
                if (admin == null)
                {
                    return HttpNotFound();
                }
                return View(admin);
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login"); }
        }

        public ActionResult ListAll()
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login");
                }
                return View(db.Admins.ToList());
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login"); }
        }

        // GET: Admins/Create
        public ActionResult Create()
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login");
                }
                return View();
            }
            catch(NullReferenceException nosession) { return RedirectToAction("Login"); }
        }

        // POST: Admins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,username,email,password")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Admins.Add(admin);
                db.SaveChanges();
                return RedirectToAction("ListAll");
            }

            return View(admin);
        }

        // GET: Admins/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Admin admin = db.Admins.Find(id);
                if (admin == null)
                {
                    return HttpNotFound();
                }
                return View(admin);
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login"); }
        }

        // POST: Admins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,username,email,password")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(admin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListAll");
            }
            return View(admin);
        }

        // GET: Admins/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Admin admin = db.Admins.Find(id);
                if (admin == null)
                {
                    return HttpNotFound();
                }
                return View(admin);
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login"); }
        }

        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Admin admin = db.Admins.Find(id);
            db.Admins.Remove(admin);
            db.SaveChanges();
            return RedirectToAction("ListAll");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SuDiscussions_Mk2/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SuDiscussionsDAO;

namespace SuDiscussions_Mk2.Controllers
{
    public class AnswersController : Controller
    {
        private SuDiscussDBEntities db = new SuDiscussDBEntities();

        public ActionResult PostAnswer(int? qid)
        {
            if (qid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Session["qid"] = qid;
            Question question = db.Questions.Find(qid);
            Answer answer = new Answer();
            answer.questionid = (int)qid;
            answer.Question = question;
            return View(answer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostAnswer([Bind(Include = "id,description,userid,questionid")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                answer.questionid = (int)Session["qid"];
                answer.userid = (int)Session["id"];
                db.Answers.Add(answer);
                db.SaveChanges();
                return RedirectToAction("ViewQuestion", "Questions", new { id = answer.questionid });
            }
            return View(answer);
        }

        public ActionResult EditPost(int? id)
        {
            try
            {
                if ((int)Session["logged_in"] == 0)
                {
                    return RedirectToAction("Login", "Users");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Answer answer = db.Answers.Find(id);
                if (answer == null)
                {
                    return HttpNotFound();
                }
                if ((int)Session["id"] != answer.userid)
                {
                    return RedirectToAction("Logout", "Users");
                }
                return View(answer);
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login", "Users"); }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost([Bind(Include = "id,description,userid,questionid")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(answer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ViewQuestion","Questions",new { id = answer.questionid });
            }
            return View(answer);
        }

        public ActionResult DeletePost(int? id)
        {
            try
            {
                if ((int)Session["logged_in"] == 0)
                {
                    return RedirectToAction("Login", "Users");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Answer answer = db.Answers.Find(id);
                if (answer == null)
                {
                    return HttpNotFound();
                }
                if ((int)Session["id"] != answer.userid)
                {
                    return RedirectToAction("Logout", "Users");
                }
                return View(answer);
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login", "Users"); }
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("DeletePost")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePostConfirmed(int id)
        {
            Answer answer = db.Answers.Find(id);
            int qid = answer.questionid;
            db.Answers.Remove(answer);
            db.SaveChanges();
            return RedirectToAction("ViewQuestion","Questions",new { id = qid });
        }

        // GET: Answers
        public ActionResult Index()
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login", "Admins");
                }
                var answers = db.Answers.Include(a => a.Question).Include(a => a.User);
                return View(answers.ToList());
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login", "Admins"); }
        }

        // GET: Answers/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login", "Admins");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Answer answer = db.Answers.Find(id);
                if (answer == null)
                {
                    return HttpNotFound();
                }
                return View(answer);
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login", "Admins"); }
        }

        // GET: Answers/Create
        public ActionResult Create()
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login", "Admins");
                }
                ViewBag.questionid = new SelectList(db.Questions, "id", "title");
                ViewBag.userid = new SelectList(db.Users, "id", "firstname");
                return View();
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login", "Admins"); }
        }

        // POST: Answers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,description,userid,questionid")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Answers.Add(answer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.questionid = new SelectList(db.Questions, "id", "title", answer.questionid);
            ViewBag.userid = new SelectList(db.Users, "id", "firstname", answer.userid);
            return View(answer);
        }

        // GET: Answers/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login", "Admins");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Answer answer = db.Answers.Find(id);
                if (answer == null)
                {
                    return HttpNotFound();
                }
                ViewBag.questionid = new SelectList(db.Questions, "id", "title", answer.questionid);
                ViewBag.userid = new SelectList(db.Users, "id", "firstname", answer.userid);
                return View(answer);
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login", "Admins"); }
        }

        // POST: Answers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,description,userid,questionid")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(answer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.questionid = new SelectList(db.Questions, "id", "title", answer.questionid);
            ViewBag.userid = new SelectList(db.Users, "id", "firstname", answer.userid);
            return View(answer);
        }

        // GET: Answers/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login", "Admins");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Answer answer = db.Answers.Find(id);
                if (answer == null)
                {
                    return HttpNotFound();
                }
                return View(answer);
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login", "Admins"); }
        }

        // POST: Answers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Answer answer = db.Answers.Find(id);
            db.Answers.Remove(answer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SuDiscussions_Mk2/Views/Questions/Create.cshtml
@model SuDiscussionsDAO.Question

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.description, 5, 100, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userid, "userid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("userid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.userid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.topic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.topic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.topic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListAll")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SuDiscussions_Mk2/Views/Questions/Delete.cshtml
@model SuDiscussionsDAO.Question

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.topic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.topic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.firstname)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "ListAll")
        </div>
    }
</div>

SuDiscussions_Mk2/Views/Questions/DeletePost.cshtml
@model SuDiscussionsDAO.Question

@{
    ViewBag.Title = "DeletePost";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<h2>Delete Post</h2>

<h3>Are you sure you want to delete this?</h3>
<div class="card row-hover pos-relative py-3 px-3 mb-3 border-warning border-top-0 border-right-0 border-bottom-0 rounded-0">
    <div class="row align-items-center">
        <div class="col-md-8 mb-3 mb-sm-0">
            <h3 class="text-primary">
                @Html.DisplayFor(model => model.title)
            </h3>
            <p class="text-sm">Posted by @Html.DisplayFor(model => model.User.firstname) @Html.DisplayFor(model => model.User.lastname)</p>
            <h5 class="text-dark">@Html.DisplayFor(model => model.description)</h5>
            <div class="text-sm op-5">@Html.DisplayFor(model => model.topic) </div>
        </div>
    </div>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger col-12" /> |
        @Html.ActionLink("Cancel", "ViewQuestion", new { id=Model.id })
    </div>
}

SuDiscussions_Mk2/Views/Questions/Details.cshtml
@model SuDiscussionsDAO.Question

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.topic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.topic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.firstname)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "ListAll")
</p>

SuDiscussions_Mk2/Views/Questions/Edit.cshtml
@model SuDiscussionsDAO.Question

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.description, 5, 100, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userid, "userid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("userid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.userid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.topic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.topic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.topic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListAll")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SuDiscussions_Mk2/Views/Questions/EditPost.cshtml
@model SuDiscussionsDAO.Question

@{
    ViewBag.Title = "EditPost";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<h2>Edit Post</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h3 class="text-primary">
        @Html.DisplayFor(model => model.title)
    </h3>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)
    @Html.HiddenFor(model => model.title)
    @Html.HiddenFor(model => model.userid)

    <div class="form-group">
        <div class="mb-3">
            @Html.EditorFor(model => model.topic, new { htmlAttributes = new { @class = "form-control", placeholder = "TOPIC", @required = "required" } })
            @Html.ValidationMessageFor(model => model.topic, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="mb-3">
            @Html.TextAreaFor(model => model.description, 5, 100, new { @class = "form-control", placeholder = "Description...", @required = "required" })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-secondary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Cancel", "ViewQuestion", new { id = Model.id})
</div>

SuDiscussions_Mk2/Views/Questions/Index.cshtml
@model IEnumerable<SuDiscussionsDAO.Question>

@{
    ViewBag.Title = "Index";
    try
    {
        if (@Session["logged_in"].ToString().Equals("1"))
        {
            Layout = "~/Views/Shared/_LoginLayout.cshtml";
        }
    }
    catch (NullReferenceException nosession) { }
}

<h1>FORUM</h1>


@using (Html.BeginForm())
{
    <div class="input-group rounded py-2">
        @Html.TextBox("search", "", new { @class = "form-control rounded", @placeholder = "Search" })
        <input type="submit" value="&#xf002" class="btn fa fa-search">
    </div>
}


<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="card row-hover pos-relative py-3 px-3 mb-3 border-warning border-top-0 border-right-0 border-bottom-0 rounded-0">
                <div class="row align-items-center">
                    <div class="col-md-8 mb-3 mb-sm-0">
                        <h5 class="text-primary">
                            @Html.ActionLink(item.title, "ViewQuestion", new { id = item.id })
                        </h5>
                        <p class="text-sm"><span class="op-6">Posted by</span> @Html.ActionLink(item.User.firstname + " " + item.User.lastname, "UserProfile", "Users", new { id = item.userid }, new { @class = "text-black" })</p>
                        <div class="text-sm op-5"> <p class="text-black mr-2">@Html.DisplayFor(modelItem => item.topic)</p></div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

SuDiscussions_Mk2/Views/Questions/ViewQuestion.cshtml
@model SuDiscussionsDAO.Question

@{
    ViewBag.Title = "ViewQuestion";
    try
    {
        if (@Session["logged_in"].ToString().Equals("1"))
        {
            Layout = "~/Views/Shared/_LoginLayout.cshtml";
        }
    }
    catch (NullReferenceException nosession) { }
}


<div class="card row-hover pos-relative py-3 px-3 mb-3 border-warning border-top-0 border-right-0 border-bottom-0 rounded-0">
    <div class="row align-items-center">
        <div class="col-md-8 mb-3 mb-sm-0">
            <h3 class="text-primary">
                @Html.DisplayFor(model => model.title)
            </h3>
            <p class="text-sm">Posted by @Html.ActionLink(Model.User.firstname + " " + Model.User.lastname, "UserProfile", "Users", new { id = Model.userid }, new { @class = "text-secondary" })</p>
            <h5 class="text-dark">@Html.DisplayFor(model => model.description)</h5>
            <div class="text-sm op-5">@Html.DisplayFor(model => model.topic) </div>
        </div>
        @{
            try
            {
                if (@Session["logged_in"].ToString().Equals("1"))
                {
                    <div class="col-md-4 op-7">
                        <div class="row text-center op-7">
                            <div class="col px-1">@Html.ActionLink("Post Answer", "PostAnswer", "Answers", new { qid = Model.id }, new { @class = "text-primary" })</div>
                            @{
                                if ((int)@Session["id"] == Model.User.id)
                                {
                                    <div class="col px-1">@Html.ActionLink("Edit", "EditPost", new { id = Model.id }, new { @class = "text-sm text-secondary" })</div>
                                    <div class="col px-1">@Html.ActionLink("Delete", "DeletePost", new { id = Model.id }, new { @class = "text-sm text-danger" })</div>
                                }
                            }
                        </div>
                    </div>
                }
            }catch(NullReferenceException nosession) { }
        }
    </div>
</div>
<h5 class="text-secondary">Answers:</h5>
@{
    foreach (var item in Model.Answers)
    {
        <div class="px-5">
            <div class="card row-hover pos-relative py-3 px-3 mb-3 border-danger border-top-0 border-right-0 border-bottom-0 rounded-0">
                <div class="row align-items-center">
                    <div class="col-md-8 mb-3 mb-sm-0">
                        <p class="text-sm">Posted by @Html.ActionLink(item.User.firstname + " " + item.User.lastname, "UserProfile", "Users", new { id = item.userid }, new { @class = "text-secondary" })</p>
                        <h5 class="text-dark">@Html.DisplayFor(modelItem => item.description)</h5>
                    </div>
                    @{
                        try
                        {
                            if (@Session["logged_in"].ToString().Equals("1") && (int)@Session["id"] == item.User.id)
                            {
                                <div class="col-md-4 op-7">
                                    <div class="row text-center op-7">
                                        <div class="col px-1">@Html.ActionLink("Edit", "EditPost", "Answers", new { id = item.id }, new { @class = "text-sm text-secondary" })</div>
                                        <div class="col px-1">@Html.ActionLink("Delete", "DeletePost", "Answers", new { id = item.id }, new { @class = "text-sm text-danger" })</div>
                                    </div>
                                </div>
                            }
                        }catch (NullReferenceException nosession) { }
                    }
                </div>
            </div>
        </div>
                        }
}