SuDiscussions_Mk2/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SuDiscussionsDAO;

namespace SuDiscussions_Mk2.Controllers
{
    public class AdminsController : Controller
    {
        private SuDiscussDBEntities db = new SuDiscussDBEntities();

        // GET: Admins
        public ActionResult Index()
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login");
                }
                return View();
            }
            catch(NullReferenceException nosession) { return RedirectToAction("Login"); }
        }

        public ActionResult Login()
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 1)
                    return RedirectToAction("Logout");

                return View();
            }
            catch(NullReferenceException nosesion) { return View();     }
        }

        [HttpPost]
        public ActionResult Login(Admin admin)
        {
            var L1 = from adm in db.Admins orderby adm.id select adm;

            if (ModelState.IsValid)
            {


                foreach (Admin adminlist in L1)
                {
                    if (adminlist.username == admin.username && adminlist.password == admin.password)
                    {
                        this.Session["loggedin_admin"] = 1;

                        return RedirectToAction("Index");
                    }

                }
                ModelState.AddModelError("incorrect", "Username or Password Incorrect!");
            }
            return View(admin);
        }

        public ActionResult Logout()
        {
            this.Session["loggedin_admin"] = 0;

            return RedirectToAction("Login");
        }

        // GET: Admins/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Admin admin = db.Admins.Find(id);
                if (admin == null)
                {
                    return HttpNotFound();
                }
                return View(admin);
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login"); }
        }

        public ActionResult ListAll()
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login");
                }
                return View(db.Admins.ToList());
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login"); }
        }

        // GET: Admins/Create
        public ActionResult Create()
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login");
                }
                return View();
            }
            catch(NullReferenceException nosession) { return RedirectToAction("Login"); }
        }

        // POST: Admins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,username,email,password")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Admins.Add(admin);
                db.SaveChanges();
                return RedirectToAction("ListAll");
            }

            return View(admin);
        }

        // GET: Admins/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Admin admin = db.Admins.Find(id);
                if (admin == null)
                {
                    return HttpNotFound();
                }
                return View(admin);
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login"); }
        }

        // POST: Admins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,username,email,password")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(admin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListAll");
            }
            return View(admin);
        }

        // GET: Admins/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Admin admin = db.Admins.Find(id);
                if (admin == null)
                {
                    return HttpNotFound();
                }
                return View(admin);
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login"); }
        }

        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Admin admin = db.Admins.Find(id);
            db.Admins.Remove(admin);
            db.SaveChanges();
            return RedirectToAction("ListAll");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SuDiscussions_Mk2/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SuDiscussionsDAO;

namespace SuDiscussions_Mk2.Controllers
{
    public class QuestionsController : Controller
    {
        private SuDiscussDBEntities db = new SuDiscussDBEntities();
        
        // GET: Questions
        public ActionResult Index(string search)
        {
            var questions = db.Questions.Include(q => q.User);
            if (!string.IsNullOrEmpty(search))
            {
                questions = questions.Where(q => q.title.Contains(search) || q.topic.Contains(search));
            }
            return View(questions.ToList());
        }

        public ActionResult ListAll()
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login", "Admins");
                }
                var questions = db.Questions.Include(q => q.User);
                return View(questions.ToList());
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login", "Admins"); }
        }

        public ActionResult PostQuestion()
        {
            try
            {
                if ((int)Session["logged_in"] == 1)
                {
                    //ViewBag.userid = new SelectList(db.Users, "id", "firstname");
                    return View();
                }
                return RedirectToAction("Login", "Users");
            }
            catch(NullReferenceException nosession) { return RedirectToAction("Login", "Users"); }
        }

        // POST: Questions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostQuestion([Bind(Include = "id,title,description,userid,topic")] Question question)
        {
            if (ModelState.IsValid)
            {
                question.userid = (int)Session["id"];
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

 //           ViewBag.userid = new SelectList(db.Users, "id", "firstname", question.userid);
            return View(question);
        }

        public ActionResult ViewQuestion(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        public ActionResult EditPost(int? id)
        {
            try
            {
                if ((int)Session["logged_in"] == 0)
                {
                    return RedirectToAction("Login", "Users");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Question question = db.Questions.Find(id);
                if (question == null)
                {
                    return HttpNotFound();
                }
                if ((int)Session["id"] != question.userid)
                {
                    return RedirectToAction("Logout", "Users");
                }
                return View(question);
            }
            catch(NullReferenceException nosession) { return RedirectToAction("Login", "Users"); }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost([Bind(Include = "id,title,description,userid,topic")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ViewQuestion",new { id = question.id});
            }
            return View(question);
        }

        public ActionResult DeletePost(int? id)
        {
            try
            {
                if ((int)Session["logged_in"] == 0)
                {
                    return RedirectToAction("Login", "Users");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Question question = db.Questions.Find(id);
                if (question == null)
                {
                    return HttpNotFound();
                }
                if ((int)Session["id"] != question.userid)
                {
                    return RedirectToAction("Logout", "Users");
                }
                return View(question);
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login", "Users"); }
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("DeletePost")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePostConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            if(question.Answers != null)
            {
                foreach(Answer answer in question.Answers.ToList())
                {
                    db.Answers.Remove(answer);
                }   
            }
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login", "Admins");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Question question = db.Questions.Find(id);
                if (question == null)
                {
                    return HttpNotFound();
                }
                return View(question);
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login", "Admins"); }
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login", "Admins");
                }
                ViewBag.userid = new SelectList(db.Users, "id", "firstname");
                return View();
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login", "Admins"); }
        }

        // POST: Questions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,title,description,userid,topic")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("ListAll");
            }

            ViewBag.userid = new SelectList(db.Users, "id", "firstname", question.userid);
            return View(question);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login", "Admins");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Question question = db.Questions.Find(id);
                if (question == null)
                {
                    return HttpNotFound();
                }
                ViewBag.userid = new SelectList(db.Users, "id", "firstname", question.userid);
                return View(question);
            }
            catch (NullReferenceException nosession) { return RedirectToAction("Login", "Admins"); }
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,title,description,userid,topic")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListAll");
            }
            ViewBag.userid = new SelectList(db.Users, "id", "firstname", question.userid);
            return View(question);
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if ((int)Session["loggedin_admin"] == 0)
                {
                    return RedirectToAction("Login", "Admins");
                }
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Question question = db.Questions.Find(id);
                if (question == null)
                {
                    return HttpNotFound();
                }
                return View(question);
            }

SuDiscussions_Mk2/Views/Users/Create.cshtml
@model SuDiscussionsDAO.User

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2", Type = "password" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SuDiscussions_Mk2/Views/Users/Delete.cshtml
@model SuDiscussionsDAO.User

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SuDiscussions_Mk2/Views/Users/Details.cshtml
@model SuDiscussionsDAO.User

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SuDiscussions_Mk2/Views/Users/Edit.cshtml
@model SuDiscussionsDAO.User

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SuDiscussions_Mk2/Views/Users/Index.cshtml
@model IEnumerable<SuDiscussionsDAO.User>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.firstname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.lastname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.password)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.id }, new{ @class = "btn btn-outline-primary" })
            @Html.ActionLink("Details", "Details", new { id = item.id }, new{ @class = "btn btn-outline-secondary" })
            @Html.ActionLink("Delete", "Delete", new { id = item.id }, new{ @class = "btn btn-outline-danger" })
        </td>
    </tr>
}

</table>
<p>
    @Html.ActionLink("Back to Dashboard", "Index", "Admins")
</p>

SuDiscussions_Mk2/Views/Users/Login.cshtml
@model SuDiscussionsDAO.User

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>User</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-outline mb-4">
        <div class="col-md-10">
            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", placeholder = "Email", @required = "required" } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-outline mb-4">
        <div class="col-md-10">
            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control", placeholder = "Password", type = "password",@required = "required" } })
            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Login" class="btn btn-primary col-12 mb-4" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Not a member?", "Register")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SuDiscussions_Mk2/Views/Users/Register.cshtml
@model SuDiscussionsDAO.User

@{
        ViewBag.Title = "Register";
}

<h2>Register</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>User</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="col-md-10">
            @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control", placeholder = "First Name", @required = "required" } })
            @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-10">
            @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control", placeholder = "Last Name", @required = "required" } })
            @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-10">
            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", placeholder = "Email", @required = "required" } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-10">
            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control", type = "password", placeholder = "Password", @required = "required" } })
            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Register" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Already a member?", "Login")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SuDiscussions_Mk2/Views/Users/UserProfile.cshtml
@model SuDiscussionsDAO.User

@{
    ViewBag.Title = "UserProfile";
    try
    {
        if (@Session["logged_in"].ToString().Equals("1"))
        {
            Layout = "~/Views/Shared/_LoginLayout.cshtml";
        }
    }
    catch (NullReferenceException nosession) { }
}

<div class="card text-center">
    <div class="card-header">
        Profile
    </div>
    <div class="card-body">
        <h3 class="card-title">@Html.DisplayFor(model => model.firstname) @Html.DisplayFor(model => model.lastname)</h3>
        <p class="card-text">Posts : @Html.DisplayFor(model => model.Questions.Count)</p>
    </div>
</div>

<h4>Posts by user : </h4>
<div class="container">
    <div class="row">
        @foreach (var item in Model.Questions)
        {
            <div class="card row-hover pos-relative py-3 px-3 mb-3 border-primary border-top-0 border-right-0 border-bottom-0 rounded-0">
                <div class="row align-items-center">
                    <div class="col-md-8 mb-3 mb-sm-0">
                        <h5>
                            @Html.ActionLink(item.title, "ViewQuestion","Questions", new { id = item.id }, new { @class="text-primary" })
                        </h5>
                        <p class="text-sm"><span class="op-6">Posted by</span> @Html.ActionLink(item.User.firstname + " " + item.User.lastname, "UserProfile", "Users", new { id = item.userid }, new { @class = "text-black" })</p>
                        <div class="text-sm op-5"> <p class="text-black mr-2">@Html.DisplayFor(modelItem => item.topic)</p></div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>